---
all:
  hosts:
    # UbuntuDev:
    #  ansible_port: 22
    #  ansible_host: ubuntudev.int.zeller.sh
    #  software: [ubuntu, docker, autoupdate, new]
    MS01-Debian:
      ansible_port: 22
      ansible_host: 192.168.5.50
      software: [debian, docker, autoupdate, new, apt]
    ReverseProxy:
      ansible_port: 22
      ansible_host: 159.195.157.59
      software: [ubuntu, docker, autoupdate, new, apt]
    JumpServer:
      ansible_port: 22
      ansible_host: 192.168.5.28
      software: [ubuntu, autoupdate, new, apt]
    Games:
      ansible_port: 22
      ansible_host: 192.168.5.25
      software: [ubuntu, docker, autoupdate, new, php, apt]
    Kasm:
      ansible_port: 22
      ansible_host: 192.168.5.27
      software: [ubuntu, docker, autoupdate, new, apt]
    Router02:
      ansible_port: 22
      ansible_host: router02.int.zeller.sh
      software: [opnsense]
    MS01:
      ansible_port: 22
      ansible_host: ms01.int.zeller.sh
      software: [ubuntu, docker, autoupdate, new, apt]
    App01:
      ansible_port: 22
      ansible_host: app01.int.zeller.sh
      software: [ubuntu, docker, autoupdate, new, apt]
    DOH01:
      ansible_port: 22
      ansible_host: DOH01.int.zeller.sh
      software: [redhat, docker, autoupdate]
    Movies:
      ansible_port: 22
      ansible_host: movies.int.zeller.sh
      software: [ubuntu, autoupdate, jellyfin, apt]
    VMH01:
      software: [proxmox, autoupdate, apt]
      ansible_port: 22
      ansible_host: vmh01.int.zeller.sh
    VMH02:
      software: [proxmox, autoupdate, apt]
      ansible_port: 22
      ansible_host: vmh02.int.zeller.sh
    VMH03:
      software: [proxmox, autoupdate, apt]
      ansible_port: 22
      ansible_host: vmh03.int.zeller.sh
    WEB:
      ansible_port: 22
      ansible_host: web.zeller.sh
      software: [ubuntu, autoupdate, docker, new, apt]
    VPN:
      ansible_port: 22
      ansible_host: vpn.zeller.sh
      software: [ubuntu, autoupdate, docker, new, apt]
    STO01:
      software: [truenas]
    STO02:
      software: [truenas]
    HA01:
      software: [homeassistant]
    HA02:
      software: [homeassistant]
    HA03:
      software: [homeassistant]
    DC01:
      software: [windows]
    DC02:
      software: [windows]
    DC03:
      software: [windows]
