---
all:
  hosts:
    RedhatDev:
      ansible_port: 22
      ansible_host: RedhatDev.int.zeller.sh
      tags: [redhat, docker, autoupdate]
    #UbuntuDev:
    #  ansible_port: 22
    #  ansible_host: ubuntudev.int.zeller.sh
    #  tags: [ubuntu, docker, autoupdate, new]
    ReverseProxy:
      ansible_port: 22
      ansible_host: 192.168.5.24
      tags: [ubuntu, docker, autoupdate, new]
    GamesZeller:
      ansible_port: 22
      ansible_host: 192.168.5.25
      tags: [ubuntu, docker, autoupdate, new, php]
    Router02:
      ansible_port: 22
      ansible_host: router02.int.zeller.sh
      tags: [opnsense]
    MS01:
      ansible_port: 22
      ansible_host: ms01.int.zeller.sh
      tags: [ubuntu, docker, autoupdate, new]
    DOH01:
      ansible_port: 22
      ansible_host: DOH01.int.zeller.sh
      tags: [redhat, docker, autoupdate]
    Movies:
      tags: [ubuntu, autoupdate, jellyfin]
    VMH01:
      tags: [ubuntu, autoupdate]
    VMH02:
      tags: [ubuntu, autoupdate]
    WEB:
      tags: [ubuntu, autoupdate, docker]
    Games:
      tags: [ubuntu, autoupdate, docker]
    STO01:
      tags: [truenas]
    STO02:
      tags: [truenas]
    HA01:
      tags: [homeassistant]
    HA02:
      tags: [homeassistant]
    HA03:
      tags: [homeassistant]
    DC01:
      tags: [windows]
    DC02:
      tags: [windows]
    DC03:
      tags: [windows]
