---
all:
  hosts:
    #UbuntuDev:
    #  ansible_port: 22
    #  ansible_host: ubuntudev.int.zeller.sh
    #  tags: [ubuntu, docker, autoupdate, new]
    ReverseProxy:
      ansible_port: 22
      ansible_host: 192.168.5.24
      tags: [ubuntu, docker, autoupdate, new, apt]
    Games:
      ansible_port: 22
      ansible_host: 192.168.5.25
      tags: [ubuntu, docker, autoupdate, new, php, apt]
    Router02:
      ansible_port: 22
      ansible_host: router02.int.zeller.sh
      tags: [opnsense]
    MS01:
      ansible_port: 22
      ansible_host: ms01.int.zeller.sh
      tags: [ubuntu, docker, autoupdate, new, apt]
    App01:
      ansible_port: 22
      ansible_host: app01.int.zeller.sh
      tags: [ubuntu, docker, autoupdate, new, apt]
    DOH01:
      ansible_port: 22
      ansible_host: DOH01.int.zeller.sh
      tags: [redhat, docker, autoupdate]
    Movies:
      ansible_port: 22
      ansible_host: movies.int.zeller.sh
      tags: [ubuntu, autoupdate, jellyfin, apt]
    VMH01:
      tags: [proxmox, autoupdate, apt]
      ansible_port: 22
      ansible_host: vmh01.int.zeller.sh
    VMH02:
      tags: [proxmox, autoupdate, apt]
      ansible_port: 22
      ansible_host: vmh02.int.zeller.sh
    VMH03:
      tags: [proxmox, autoupdate, apt]
      ansible_port: 22
      ansible_host: vmh03.int.zeller.sh
    WEB:
      ansible_port: 22
      ansible_host: web.zeller.sh
      tags: [ubuntu, autoupdate, docker, new, apt]
    STO01:
      tags: [truenas]
    STO02:
      tags: [truenas]
    HA01:
      tags: [homeassistant]
    HA02:
      tags: [homeassistant]
    HA03:
      tags: [homeassistant]
    DC01:
      tags: [windows]
    DC02:
      tags: [windows]
    DC03:
      tags: [windows]
