---
plugin: ansible.builtin.constructed
strict: false
groups:
  redhat: "'redhat' in software"
  ubuntu: "'ubuntu' in software"
  debian: "'debian' in software"
  opnsense: "'opnsense' in software"
  windows: "'windows' in software"
  truenas: "'truenas' in software"
  homeassistant: "'homeassistant' in software"
  autoupdate: "'autoupdate' in software"
  podman: "'podman' in software"
  docker: "'docker' in software"
  new: "'new' in software"
  php: "'php' in software"
  proxmox: "'proxmox' in software"
  apt: "'apt' in software"
