---
plugin: ansible.builtin.constructed
strict: false
groups:
  redhat: "'redhat' in tags"
  ubuntu: "'ubuntu' in tags"
  debian: "'debian' in tags"
  opnsense: "'opnsense' in tags"
  windows: "'windows' in tags"
  truenas: "'truenas' in tags"
  homeassistant: "'homeassistant' in tags"
  autoupdate: "'autoupdate' in tags"
  podman: "'podman' in tags"
  docker: "'docker' in tags"
  new: "'new' in tags"
  php: "'php' in tags"
  proxmox: "'proxmox' in tags"
