- name: Install Docker
  become: true
  become_method: ansible.builtin.sudo
  hosts: debian:&docker:&new
  ignore_unreachable: true
  gather_facts: true
  tasks:
    - name: Install Repo
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/debian
        suites: '{{ ansible_facts["distribution_release"] }}'
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/debian/gpg
        state: present
    - name: APT Update
      ansible.builtin.apt:
        update_cache: true
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
    - name: Create Default Docker user
      ansible.builtin.user:
        name: dockerservice
        create_home: false
        state: present
        shell: /bin/bash
        groups:
          - docker
    - name: Add existing user '{{ user }}' to group sudo
      ansible.builtin.user:
        name: 'andreas'
        groups: docker
        append: true
    - name: Create Docker Folder
      ansible.builtin.file:
        path: /_zeller
        state: directory
        mode: "0755"
        owner: dockerservice
        group: dockerservice
